# Generated by Django 5.2.6 on 2025-09-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='universitycourse',
            name='unique course and semester',
        ),
        migrations.RenameField(
            model_name='universitycourse',
            old_name='course',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='universitycourse',
            old_name='university',
            new_name='universities',
        ),
        migrations.AddConstraint(
            model_name='universitycourse',
            constraint=models.UniqueConstraint(fields=('courses', 'semester'), name='unique courses and semester'),
        ),
    ]
