# Generated by Django 5.2.6 on 2025-09-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_remove_universitycourse_unique_course_and_semester_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='universitycourse',
            name='unique courses and semester',
        ),
        migrations.RenameField(
            model_name='universitycourse',
            old_name='courses',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='universitycourse',
            old_name='universities',
            new_name='university',
        ),
        migrations.AddConstraint(
            model_name='universitycourse',
            constraint=models.UniqueConstraint(fields=('course', 'semester'), name='unique course and semester'),
        ),
    ]
