# Generated by Django 5.2.6 on 2025-09-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_remove_universitycourse_unique_courses_and_semester_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='universitycourse',
            name='unique course and semester',
        ),
        migrations.AddConstraint(
            model_name='universitycourse',
            constraint=models.UniqueConstraint(fields=('course', 'semester', 'university'), name='unique course and semester and university'),
        ),
    ]
